export interface Account {
    code: string;
    name: string;
    type: 'Asset' | 'Liability' | 'Equity' | 'Revenue' | 'Expense' | 'Other';
};

export const chartOfAccounts: Account[] = [
    // Assets
    { code: '101100', name: 'Cash at Bank - Main Account', type: 'Asset' },
    { code: '101110', name: 'Cash at Bank - Operations Account', type: 'Asset' },
    { code: '101120', name: 'Cash at Bank - Sales Collection Account', type: 'Asset' },
    { code: '101130', name: 'Cash at Hand - Head Office', type: 'Asset' },
    { code: '101140', name: 'Cash at Hand - Factory', type: 'Asset' },
    { code: '101150', name: 'Cash at Hand - Depot/Branches', type: 'Asset' },
    { code: '101200', name: 'Trade Receivables - Customers', type: 'Asset' },
    { code: '101210', name: 'Accounts Receivable Control (AUTO)', type: 'Asset' },
    { code: '101220', name: 'Staff Debtors', type: 'Asset' },
    { code: '101230', name: 'Other Receivables', type: 'Asset' },
    { code: '101240', name: 'Prepayments - Insurance', type: 'Asset' },
    { code: '101250', name: 'Prepayments - Rent', type: 'Asset' },
    { code: '101260', name: 'Prepayments - Other', type: 'Asset' },
    { code: '101300', name: 'Inventory - Raw Materials', type: 'Asset' },
    { code: '101310', name: 'Inventory Control - Raw Materials (AUTO)', type: 'Asset' },
    { code: '101320', name: 'Inventory - Work-in-Progress', type: 'Asset' },
    { code: '101330', name: 'Inventory Control - WIP (AUTO)', type: 'Asset' },
    { code: '101340', name: 'Inventory - Finished Goods', type: 'Asset' },
    { code: '101350', name: 'Inventory Control - Finished Goods (AUTO)', type: 'Asset' },
    { code: '101360', name: 'Inventory - Packaging Materials', type: 'Asset' },
    { code: '101370', name: 'Inventory - Spare Parts & Consumables', type: 'Asset' },
    { code: '101400', name: 'Inter-Branch Receivable (AUTO)', type: 'Asset' },
    { code: '101410', name: 'Withholding Tax Receivable', type: 'Asset' },
    { code: '101420', name: 'VAT Refundable (Input VAT)', type: 'Asset' },
    { code: '101430', name: 'Deposits with Suppliers', type: 'Asset' },
    { code: '102100', name: 'Property, Plant & Equipment Control (AUTO)', type: 'Asset' },
    { code: '102110', name: 'Land', type: 'Asset' },
    { code: '102120', name: 'Buildings - Factory', type: 'Asset' },
    { code: '102130', name: 'Buildings - Administrative', type: 'Asset' },
    { code: '102140', name: 'Plant & Machinery - Production Lines', type: 'Asset' },
    { code: '102150', name: 'Borehole & Water Treatment Facilities', type: 'Asset' },
    { code: '102160', name: 'Factory Generators', type: 'Asset' },
    { code: '102170', name: 'Motor Vehicles - Distribution', type: 'Asset' },
    { code: '102180', name: 'Office Equipment', type: 'Asset' },
    { code: '102190', name: 'Furniture & Fixtures', type: 'Asset' },
    { code: '102200', name: 'Capital Work-in-Progress (CWIP)', type: 'Asset' },
    { code: '102300', name: 'Intangible Assets - Software', type: 'Asset' },
    { code: '102310', name: 'Accumulated Depreciation - Buildings', type: 'Asset' },
    { code: '102320', name: 'Accumulated Depreciation - Plant & Machinery', type: 'Asset' },
    { code: '102330', name: 'Accumulated Depreciation - Motor Vehicles', type: 'Asset' },
    { code: '102340', name: 'Accumulated Depreciation - Office Equipment', type: 'Asset' },
    { code: '102350', name: 'Impairment Loss Assets', type: 'Asset' },
    // Liabilities
    { code: '201010', name: 'Accounts Payable Control (AUTO)', type: 'Liability' },
    { code: '201020', name: 'Trade Creditors - Suppliers', type: 'Liability' },
    { code: '201030', name: 'Accrued Expenses', type: 'Liability' },
    { code: '201040', name: 'Accrued Payroll', type: 'Liability' },
    { code: '201110', name: 'Payroll Control Account (AUTO)', type: 'Liability' },
    { code: '201210', name: 'VAT Output Payable', type: 'Liability' },
    { code: '201220', name: 'VAT Input Offset', type: 'Liability' },
    { code: '201230', name: 'PAYE Tax Payable', type: 'Liability' },
    { code: '201240', name: 'Withholding Tax (WHT) Payable', type: 'Liability' },
    { code: '201250', name: 'Corporate Income Tax Payable', type: 'Liability' },
    { code: '201260', name: 'Pension Payable', type: 'Liability' },
    { code: '201270', name: 'NHF Payable', type: 'Liability' },
    { code: '201280', name: 'NSITF Payable', type: 'Liability' },
    { code: '201290', name: 'Other Statutory Deductions Payable', type: 'Liability' },
    { code: '201300', name: 'Short-Term Loan - Bank OD', type: 'Liability' },
    { code: '201310', name: 'Current Portion of Long-Term Loan', type: 'Liability' },
    { code: '201400', name: 'Inter-Branch Payable (AUTO)', type: 'Liability' },
    { code: '202100', name: 'Long-Term Loan - Bank', type: 'Liability' },
    // Equity
    { code: '301000', name: 'Share Capital', type: 'Equity' },
    { code: '302000', name: 'Retained Earnings', type: 'Equity' },
    { code: '303000', name: 'Current Year Earnings', type: 'Equity' },
    // Revenue
    { code: '401000', name: 'Sales - Finished Goods', type: 'Revenue' },
    { code: '402000', name: 'Sales Returns and Allowances', type: 'Revenue' },
    { code: '403000', name: 'Other Income', type: 'Revenue' },
    // Expenses
    { code: '501000', name: 'Cost of Goods Sold', type: 'Expense' },
    { code: '502000', name: 'Salaries and Wages', type: 'Expense' },
    { code: '503000', name: 'Rent Expense', type: 'Expense' },
    { code: '504000', name: 'Utilities', type: 'Expense' },
    { code: '505000', name: 'Marketing Expenses', type: 'Expense' },
    { code: '506000', name: 'Depreciation Expense', type: 'Expense' },
    { code: '507000', name: 'Bank Charges', type: 'Expense' },
    { code: '599999', name: 'Miscellaneous Expenses', type: 'Expense' },
];
