export const defaultChartOfAccounts = [
  { account_code: '101000', account_name: 'Cash & Cash Equivalents (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101100', account_name: 'Cash at Bank - Main Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101110', account_name: 'Cash at Bank - Operations Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101120', account_name: 'Cash at Bank - Sales Collection Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101130', account_name: 'Cash at Hand - Head Office', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101140', account_name: 'Cash at Hand - Factory', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101150', account_name: 'Cash at Hand - Depot/Branches', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '102000', account_name: 'Accounts Receivable (AUTO)', account_type: 'Asset', system_role: 'ACCOUNTS_RECEIVABLE', parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '102100', account_name: 'Trade Receivables - Customers', account_type: 'Asset', system_role: null, parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102200', account_name: 'Staff Debtors', account_type: 'Asset', system_role: null, parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102300', account_name: 'Other Receivables', account_type: 'Asset', system_role: null, parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102400', account_name: 'Prepayments (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '102410', account_name: 'Prepayments - Insurance', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '102420', account_name: 'Prepayments - Rent', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '102430', account_name: 'Prepayments - Other', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '103000', account_name: 'Inventory Control (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '103100', account_name: 'Inventory - Raw Materials', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103110', account_name: 'Inventory - Spare Parts & Consumables', account_type: 'Asset', system_role: 'INVENTORY_CONSUMABLES', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103200', account_name: 'Inventory - Work-in-Progress', account_type: 'Asset', system_role: 'INVENTORY_WIP', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103300', account_name: 'Inventory - Finished Goods', account_type: 'Asset', system_role: 'INVENTORY_FINISHED_GOODS', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103310', account_name: 'Inventory - Packaging Materials', account_type: 'Asset', system_role: 'INVENTORY_PACKAGING', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '104000', account_name: 'Property, Plant & Equipment (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '104100', account_name: 'Land', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104200', account_name: 'Buildings', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104300', account_name: 'Plant & Machinery', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104400', account_name: 'Motor Vehicles', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104500', account_name: 'Office Equipment', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104600', account_name: 'Furniture & Fixtures', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104700', account_name: 'Capital Work-in-Progress (CWIP)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '105000', account_name: 'Intangible Assets', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '105100', account_name: 'Software', account_type: 'Asset', system_role: null, parent_account_code: '105000', is_control_account: false, is_active: true },
  { account_code: '105200', account_name: 'Accumulated Depreciation', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '105210', account_name: 'Accumulated Depreciation - Buildings', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105220', account_name: 'Accumulated Depreciation - Plant & Machinery', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105230', account_name: 'Accumulated Depreciation - Motor Vehicles', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105240', account_name: 'Accumulated Depreciation - Office Equipment', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105250', account_name: 'Impairment Loss Assets', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '201000', account_name: 'Accounts Payable (AUTO)', account_type: 'Liability', system_role: 'accounts_payable', parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '201100', account_name: 'Trade Creditors - Suppliers', account_type: 'Liability', system_role: null, parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201200', account_name: 'Accrued Expenses', account_type: 'Liability', system_role: null, parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201300', account_name: 'Payroll Payables', account_type: 'Liability', system_role: null, parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201400', account_name: 'Statutory Payables (AUTO)', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '201410', account_name: 'VAT Output Payable', account_type: 'Liability', system_role: 'VAT_PAYABLE', parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201420', account_name: 'PAYE Tax Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201430', account_name: 'Withholding Tax Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201440', account_name: 'Pension Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201500', account_name: 'Short-Term Loan - Bank OD', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '201600', account_name: 'Long-Term Loan - Bank', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '301000', account_name: 'Share Capital', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '302000', account_name: 'Retained Earnings', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '303000', account_name: 'Current Year Earnings', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '304000', account_name: 'Opening Balance Equity', account_type: 'Equity', system_role: 'OPENING_EQUITY', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '401000', account_name: 'Sales - Finished Goods', account_type: 'Revenue', system_role: 'SALES_REVENUE', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '402000', account_name: 'Sales Returns & Allowances', account_type: 'Revenue', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '403000', account_name: 'Other Income', account_type: 'Revenue', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '501000', account_name: 'Cost of Goods Sold', account_type: 'COGS', system_role: 'COGS', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '502000', account_name: 'Salaries and Wages', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '503000', account_name: 'Rent Expense', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '504000', account_name: 'Utilities', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '505000', account_name: 'Marketing Expenses', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506000', account_name: 'Depreciation Expense', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '507000', account_name: 'Bank Charges', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '508000', account_name: 'Insurance Expense', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '599999', account_name: 'Miscellaneous Expenses', account_type: 'Expense', system_role: 'default_expense', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101200', account_name: 'Trade Receivables - Customers', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101210', account_name: 'Accounts Receivable Control (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101220', account_name: 'Staff Debtors', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101230', account_name: 'Other Receivables', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101240', account_name: 'Prepayments - Insurance', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101250', account_name: 'Prepayments - Rent', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101260', account_name: 'Prepayments - Other', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101300', account_name: 'Inventory - Raw Materials', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101310', account_name: 'Inventory Control - Raw Materials (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101320', account_name: 'Inventory - Work-in-Progress', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101330', account_name: 'Inventory Control - WIP (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101340', account_name: 'Inventory - Finished Goods', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101350', account_name: 'Inventory Control - Finished Goods (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101360', account_name: 'Inventory - Packaging Materials', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101370', account_name: 'Inventory - Spare Parts & Consumables', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101400', account_name: 'Inter-Branch Receivable (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101410', account_name: 'Withholding Tax Receivable', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101420', account_name: 'VAT Refundable (Input VAT)', account_type: 'Asset', system_role: 'input_vat', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '101430', account_name: 'Deposits with Suppliers', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true }
];

export const defaultInventoryCategoryMap = [
  { category_name: 'Consumables & Production Supplies', system_role: 'INVENTORY_CONSUMABLES' },
  { category_name: 'Finished Goods Inventory', system_role: 'INVENTORY_FINISHED_GOODS' },
  { category_name: 'Fuel & Energy Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Goods-in-Transit Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Obsolete, Expired & Scrap Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Packaging Materials Inventory', system_role: 'INVENTORY_PACKAGING' },
  { category_name: 'Promotional & Marketing Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Raw Materials Inventory', system_role: 'INVENTORY_RAW_MATERIAL' },
  { category_name: 'Rejected / Quality-Hold Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Returned Goods / Reverse Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Safety Stock / Buffer Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Spare Parts & Maintenance Inventory', system_role: 'INVENTORY_CONSUMABLES' },
  { category_name: 'Third-Party / Consignment Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Work-in-Progress (WIP) Inventory', system_role: 'INVENTORY_WIP' }
];
