CREATE TABLE `boms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `finished_good_id` int(11) NOT NULL,
  `bom_code` varchar(50) NOT NULL,
  `bom_version` varchar(20) DEFAULT '1.0',
  `status` varchar(20) DEFAULT 'Active',
  `uom` varchar(20) DEFAULT NULL,
  `batch_size` decimal(15,5) DEFAULT 1.00000,
  `effective_from` date DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `scrap_percentage` decimal(8,5) DEFAULT 0.00000,
  `prepared_by` varchar(100) DEFAULT NULL,
  `approved_by` varchar(100) DEFAULT NULL,
  `bom_type` varchar(50) DEFAULT 'Standard',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bom_code` (`bom_code`),
  KEY `company_id` (`company_id`),
  KEY `finished_good_id` (`finished_good_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;