CREATE TABLE `supplier_invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` varchar(50) NOT NULL,
  `grn_id` int(11) DEFAULT NULL COMMENT 'Link to the GRN, can be nullable if invoices can be created without a GRN',
  `purchase_order_id` int(11) DEFAULT NULL COMMENT 'Direct link to the PO',
  `supplier_id` int(11) NOT NULL,
  `invoice_number` varchar(255) NOT NULL COMMENT 'The supplier\'s own invoice number',
  `invoice_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `total_amount` decimal(15,2) NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'Draft' COMMENT 'e.g., Draft, Awaiting Approval, Approved, Partially Paid, Paid, Cancelled',
  `journal_voucher_id` int(11) DEFAULT NULL COMMENT 'Link to the journal voucher created upon approval',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique_invoice` (`company_id`,`supplier_id`,`invoice_number`),
  KEY `fk_supplier_invoices_grn` (`grn_id`),
  KEY `fk_supplier_invoices_po` (`purchase_order_id`),
  KEY `fk_supplier_invoices_supplier` (`supplier_id`),
  KEY `fk_supplier_invoices_journal_voucher` (`journal_voucher_id`),
  CONSTRAINT `fk_supplier_invoices_grn` FOREIGN KEY (`grn_id`) REFERENCES `goods_received_notes` (`id`),
  CONSTRAINT `fk_supplier_invoices_po` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`),
  CONSTRAINT `fk_supplier_invoices_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;