'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from "@/components/ui/button";
import {
  Table, TableBody, TableCell,
  TableHead, TableHeader,
  TableRow, TableFooter
} from "@/components/ui/table";
import { DatePicker } from '@/components/ui/date-picker';
import { Checkbox } from '@/components/ui/checkbox';
import { format } from 'date-fns';
import {
  Loader2, CheckCircle, AlertCircle,
  RefreshCcw, FileSpreadsheet,
  FileText, Printer, Download,
  Eye, EyeOff, Filter,
  Calendar, Search,
  FileBarChart, Scale
} from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

/* ================= HELPERS ================= */

const money = (v?: number) =>
  !v ? '-' : v.toLocaleString('en-US', { minimumFractionDigits: 2 });

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(amount);
};

/* ================= PDF EXPORT FUNCTION ================= */

const generatePDF = (sections: any, grand_totals: any, startDate: Date, endDate: Date, companyName?: string) => {
  const doc = new jsPDF('landscape');
  
  // Header with logo and title
  doc.setFillColor(10, 45, 85); // Dark blue
  doc.rect(0, 0, 297, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('TRIAL BALANCE REPORT', 148.5, 12, { align: 'center' });
  doc.setFontSize(10);
  doc.text('Financial Position Statement', 148.5, 18, { align: 'center' });
  
  // Reset colors
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(9);
  
  // Company info
  let yPos = 30;
  doc.text(`Company: ${companyName || 'Not Available'}`, 20, yPos);
  doc.text(`Report Period: ${format(startDate, 'dd MMMM yyyy')} to ${format(endDate, 'dd MMMM yyyy')}`, 200, yPos);
  yPos += 6;
  doc.text(`Generated: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, 20, yPos);
  
  // Summary
  yPos += 10;
  doc.setFillColor(240, 240, 240);
  doc.rect(20, yPos, 257, 15, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('FINANCIAL SUMMARY', 30, yPos + 8);
  yPos += 20;
  doc.setFont('helvetica', 'normal');
  
  const isBalanced = Math.abs(grand_totals.debit - grand_totals.credit) < 0.01;
  doc.text(`Status: ${isBalanced ? 'BALANCED' : 'NOT BALANCED'}`, 30, yPos);
  doc.text(`Total Debit: ${formatCurrency(grand_totals.debit)}`, 100, yPos);
  doc.text(`Total Credit: ${formatCurrency(grand_totals.credit)}`, 200, yPos);
  
  // Table data
  yPos += 15;
  const tableData: any[] = [];
  
  Object.entries(sections).forEach(([sectionName, section]: any) => {
    // Section header
    tableData.push([
      { 
        content: `${sectionName === 'COGS' ? 'COST OF GOODS SOLD' : sectionName.toUpperCase()} SECTION`, 
        colSpan: 4, 
        styles: { fillColor: [220, 220, 220], fontStyle: 'bold' } 
      }
    ]);
    
    // Accounts
    section.accounts.forEach((account: any) => {
      tableData.push([
        account.account_code,
        account.account_name,
        { content: formatCurrency(account.debit), styles: { halign: 'right' } },
        { content: formatCurrency(account.credit), styles: { halign: 'right' } }
      ]);
    });
    
    // Section total
    tableData.push([
      { content: `TOTAL ${sectionName.toUpperCase()}`, colSpan: 2, styles: { fontStyle: 'bold' } },
      { content: formatCurrency(section.total_debit), styles: { halign: 'right', fontStyle: 'bold' } },
      { content: formatCurrency(section.total_credit), styles: { halign: 'right', fontStyle: 'bold' } }
    ]);
    
    // Spacer
    tableData.push(['', '', '', '']);
  });
  
  // Grand total
  tableData.push([
    { content: 'GRAND TOTAL', colSpan: 2, styles: { fillColor: [0, 0, 0], textColor: [255, 255, 255], fontStyle: 'bold' } },
    { content: formatCurrency(grand_totals.debit), styles: { halign: 'right', fillColor: [0, 0, 0], textColor: [255, 255, 255], fontStyle: 'bold' } },
    { content: formatCurrency(grand_totals.credit), styles: { halign: 'right', fillColor: [0, 0, 0], textColor: [255, 255, 255], fontStyle: 'bold' } }
  ]);
  
  // Generate table
  (doc as any).autoTable({
    startY: yPos,
    head: [['Account Code', 'Account Name', 'Debit Balance (₦)', 'Credit Balance (₦)']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [10, 45, 85], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 8, cellPadding: 3 },
    columnStyles: {
      2: { halign: 'right' },
      3: { halign: 'right' }
    }
  });
  
  // Footer
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by ClearBooks Accounting System', 148.5, finalY, { align: 'center' });
  
  // Save PDF
  doc.save(`TrialBalance_${format(startDate, 'yyyyMMdd')}_${format(endDate, 'yyyyMMdd')}.pdf`);
};

/* ================= EXCEL EXPORT FUNCTION ================= */

const generateExcel = (sections: any, grand_totals: any, startDate: Date, endDate: Date) => {
  const wb = XLSX.utils.book_new();
  
  // Summary sheet
  const summaryData = [
    ['TRIAL BALANCE REPORT'],
    [''],
    ['Report Period:', `${format(startDate, 'dd MMMM yyyy')} to ${format(endDate, 'dd MMMM yyyy')}`],
    ['Generated:', format(new Date(), 'dd/MM/yyyy HH:mm:ss')],
    [''],
    ['Total Debit:', grand_totals.debit],
    ['Total Credit:', grand_totals.credit],
    ['Balance Status:', Math.abs(grand_totals.debit - grand_totals.credit) < 0.01 ? 'BALANCED' : 'NOT BALANCED'],
    ['']
  ];
  
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
  
  // Main data sheet
  const data: any[][] = [
    ['Section', 'Account Code', 'Account Name', 'Debit (₦)', 'Credit (₦)']
  ];
  
  Object.entries(sections).forEach(([sectionName, section]: any) => {
    section.accounts.forEach((account: any) => {
      data.push([
        sectionName,
        account.account_code,
        account.account_name,
        account.debit,
        account.credit
      ]);
    });
    
    // Add section totals
    data.push([
      sectionName + ' TOTAL',
      '',
      '',
      section.total_debit,
      section.total_credit
    ]);
    
    data.push(['', '', '', '', '']); // Empty row
  });
  
  // Add grand totals
  data.push([
    'GRAND TOTAL',
    '',
    '',
    grand_totals.debit,
    grand_totals.credit
  ]);
  
  const wsData = XLSX.utils.aoa_to_sheet(data);
  XLSX.utils.book_append_sheet(wb, wsData, 'Trial Balance');
  
  // Save Excel file
  XLSX.writeFile(wb, `TrialBalance_${format(startDate, 'yyyyMMdd')}.xlsx`);
};

/* ================= COMPONENT ================= */

export default function TrialBalancePage() {
  const { user } = useAuth();

  const [report, setReport] = useState<any>(null);
  const [startDate, setStartDate] = useState<Date>(() => {
    const date = new Date();
    date.setDate(1);
    return date;
  });
  const [endDate, setEndDate] = useState<Date>(new Date());
  const [hideZero, setHideZero] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  /* -------- FETCH -------- */

  const loadReport = async () => {
    if (!user?.company_id) return;
    setLoading(true);
    try {
      const url = new URL('https://hariindustries.net/api/clearbook/balancetrial.php');
      url.searchParams.set('company_id', user.company_id);
      url.searchParams.set('fromDate', format(startDate, 'yyyy-MM-dd'));
      url.searchParams.set('toDate', format(endDate, 'yyyy-MM-dd'));

      const res = await fetch(url.toString());
      const json = await res.json();

      if (!json.success) throw new Error(json.message);

      setReport(json);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { loadReport(); }, [user, startDate, endDate]);

  const handleExportPDF = () => {
    if (!report) return;
    generatePDF(report.report, report.grand_totals, startDate, endDate, user?.company_name);
  };

  const handleExportExcel = () => {
    if (!report) return;
    generateExcel(report.report, report.grand_totals, startDate, endDate);
  };

  const handlePrint = () => {
    // Create a print-friendly version
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const isBalanced = Math.abs(report.grand_totals.debit - report.grand_totals.credit) < 0.01;
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Trial Balance Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          .header { text-align: center; margin-bottom: 30px; }
          .header h1 { color: #1e40af; margin-bottom: 5px; }
          .company-info { margin-bottom: 20px; }
          .summary { 
            background: ${isBalanced ? '#d1fae5' : '#fee2e2'}; 
            padding: 15px; 
            border-radius: 5px; 
            margin-bottom: 20px; 
            display: flex; 
            justify-content: space-between;
          }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
          th { background: #f3f4f6; padding: 10px; text-align: left; border: 1px solid #d1d5db; }
          td { padding: 8px; border: 1px solid #d1d5db; }
          .section-header { font-weight: bold; }
          .asset { background: #dbeafe; }
          .liability { background: #fef3c7; }
          .equity { background: #d1fae5; }
          .revenue { background: #e0e7ff; }
          .cogs { background: #f3f4f6; }
          .expense { background: #fee2e2; }
          .debit { color: #059669; text-align: right; }
          .credit { color: #dc2626; text-align: right; }
          .total-row { background: #1f2937; color: white; font-weight: bold; }
          .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #6b7280; }
          @media print {
            .no-print { display: none; }
            body { margin: 0; }
            .header { margin-top: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Trial Balance Report</h1>
          <p>Period: ${format(startDate, 'MMMM dd, yyyy')} to ${format(endDate, 'MMMM dd, yyyy')}</p>
          <p>Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}</p>
        </div>
        
        <div class="company-info">
          <p><strong>Company:</strong> ${user?.company_name || user?.company_id || 'N/A'}</p>
        </div>
        
        <div class="summary">
          <span>
            ${isBalanced ? '✓ BALANCED' : '✗ NOT BALANCED'}
          </span>
          <span>
            Total Debit: ${money(report.grand_totals.debit)} | Total Credit: ${money(report.grand_totals.credit)}
          </span>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Account Number</th>
              <th>Account Name</th>
              <th style="text-align: right;">Debit Balance</th>
              <th style="text-align: right;">Credit Balance</th>
            </tr>
          </thead>
          <tbody>
            ${Object.entries(report.report).map(([sectionName, section]: any) => {
              const accounts = hideZero
                ? section.accounts.filter((a: any) => a.debit !== 0 || a.credit !== 0)
                : section.accounts;
              
              let sectionClass = '';
              switch(sectionName) {
                case 'Asset': sectionClass = 'asset'; break;
                case 'Liability': sectionClass = 'liability'; break;
                case 'Equity': sectionClass = 'equity'; break;
                case 'Revenue': sectionClass = 'revenue'; break;
                case 'COGS': sectionClass = 'cogs'; break;
                case 'Expense': sectionClass = 'expense'; break;
              }
              
              return `
                <tr class="${sectionClass} section-header">
                  <td colspan="4">${sectionName === 'COGS' ? 'COST OF GOODS SOLD' : sectionName.toUpperCase()}</td>
                </tr>
                ${accounts.length > 0 ? accounts.map((a: any) => `
                  <tr>
                    <td>${a.account_code}</td>
                    <td>${a.account_name}</td>
                    <td class="debit">${money(a.debit)}</td>
                    <td class="credit">${money(a.credit)}</td>
                  </tr>
                `).join('') : `
                  <tr>
                    <td colspan="4" style="text-align: center; color: #9ca3af; font-style: italic;">
                      No transactions for this period
                    </td>
                  </tr>
                `}
              `;
            }).join('')}
            <tr class="total-row">
              <td colspan="2">GRAND TOTAL</td>
              <td style="text-align: right;">${money(report.grand_totals.debit)}</td>
              <td style="text-align: right;">${money(report.grand_totals.credit)}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="footer">
          <p>This report was generated by ClearBooks Accounting System</p>
          <p>${format(new Date(), 'MMMM dd, yyyy HH:mm:ss')}</p>
        </div>
        
        <div class="no-print" style="margin-top: 30px; text-align: center;">
          <button onclick="window.print()" style="padding: 10px 20px; background: #1e40af; color: white; border: none; border-radius: 5px; cursor: pointer;">
            Print Report
          </button>
          <button onclick="window.close()" style="padding: 10px 20px; margin-left: 10px; background: #6b7280; color: white; border: none; border-radius: 5px; cursor: pointer;">
            Close Window
          </button>
        </div>
        
        <script>
          // Auto-print option (uncomment if you want auto-print)
          // window.onload = function() { window.print(); }
        </script>
      </body>
      </html>
    `);
    
    printWindow.document.close();
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
      <p className="text-gray-600">Loading trial balance report...</p>
    </div>
  );
  
  if (error) return (
    <div className="text-center p-8">
      <AlertCircle className="h-12 w-12 text-red-500 mx-auto mb-4" />
      <h2 className="text-lg font-semibold text-red-700 mb-2">Error Loading Report</h2>
      <p className="text-gray-600 mb-4">{error}</p>
      <Button onClick={loadReport} variant="outline">
        <RefreshCcw className="mr-2 h-4 w-4" />
        Try Again
      </Button>
    </div>
  );

  const { report: sections, grand_totals } = report;
  const balanced = Math.abs(grand_totals.debit - grand_totals.credit) < 0.01;

  /* ================= RENDER ================= */

  return (
    <div className="p-4 md:p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 flex items-center gap-2">
            <Scale className="h-8 w-8 text-primary" />
            Trial Balance Report
          </h1>
          <p className="text-gray-600 mt-1">
            Comprehensive overview of all ledger account balances
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className={`px-3 py-1 rounded-full text-sm font-medium ${balanced ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
            {balanced ? (
              <span className="flex items-center gap-1">
                <CheckCircle className="h-4 w-4" />
                Balanced
              </span>
            ) : (
              <span className="flex items-center gap-1">
                <AlertCircle className="h-4 w-4" />
                Not Balanced
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Controls Card */}
      <Card className="shadow-sm">
        <CardContent className="pt-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Start Date</label>
              <DatePicker date={startDate} setDate={setStartDate} />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">End Date</label>
              <DatePicker date={endDate} setDate={setEndDate} />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Quick Actions</label>
              <div className="flex gap-2">
                <Button onClick={loadReport} className="flex-1" variant="outline">
                  <RefreshCcw className="mr-2 h-4 w-4" />
                  Refresh
                </Button>
                <Button onClick={() => {
                  const date = new Date();
                  date.setDate(1);
                  setStartDate(date);
                  setEndDate(new Date());
                }} variant="ghost">
                  Reset Dates
                </Button>
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Export Options</label>
              <div className="flex gap-2">
                <Button onClick={handleExportPDF} className="flex-1 bg-red-600 hover:bg-red-700">
                  <FileText className="mr-2 h-4 w-4" />
                  PDF
                </Button>
                <Button onClick={handleExportExcel} className="flex-1 bg-green-600 hover:bg-green-700">
                  <FileSpreadsheet className="mr-2 h-4 w-4" />
                  Excel
                </Button>
                <Button onClick={handlePrint} variant="outline">
                  <Printer className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
          
          <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <Checkbox 
                  id="hide-zero" 
                  checked={hideZero}
                  onCheckedChange={(v) => setHideZero(!!v)}
                />
                <label htmlFor="hide-zero" className="text-sm cursor-pointer flex items-center gap-2">
                  {hideZero ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  {hideZero ? 'Hide Zero Balances' : 'Show Zero Balances'}
                </label>
              </div>
              
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search accounts..."
                  className="pl-10 pr-3 py-2 border rounded-md text-sm w-64"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
            </div>
            
            <div className="text-sm text-gray-600">
              <Calendar className="inline h-4 w-4 mr-2" />
              {format(startDate, 'MMM dd, yyyy')} to {format(endDate, 'MMM dd, yyyy')}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Summary Banner */}
      <div className={`p-4 rounded-lg ${balanced ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center">
            <div className={`p-2 rounded-full ${balanced ? 'bg-green-100' : 'bg-red-100'} mr-3`}>
              {balanced ? (
                <CheckCircle className="h-6 w-6 text-green-600" />
              ) : (
                <AlertCircle className="h-6 w-6 text-red-600" />
              )}
            </div>
            <div>
              <h3 className="font-semibold">Financial Status: {balanced ? 'Balanced' : 'Not Balanced'}</h3>
              <p className="text-sm text-gray-600">Total Debit = Total Credit</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="text-center">
              <div className="text-lg font-bold text-green-700">{money(grand_totals.debit)}</div>
              <div className="text-sm text-gray-600">Total Debit</div>
            </div>
            <div className="text-center">
              <div className="text-lg font-bold text-red-600">{money(grand_totals.credit)}</div>
              <div className="text-sm text-gray-600">Total Credit</div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Table */}
      <Card className="overflow-hidden">
        <div className="overflow-x-auto">
          <Table className="print:table-fixed">
            <TableHeader>
              <TableRow>
                <TableHead className="font-semibold">Account Number</TableHead>
                <TableHead className="font-semibold">Account Name</TableHead>
                <TableHead className="text-right font-semibold">Debit Balance</TableHead>
                <TableHead className="text-right font-semibold">Credit Balance</TableHead>
              </TableRow>
            </TableHeader>

            <TableBody>
              {Object.entries(sections).map(([sectionName, section]: any) => {
                let accounts = hideZero
                  ? section.accounts.filter((a: any) => a.debit !== 0 || a.credit !== 0)
                  : section.accounts;

                // Apply search filter
                if (searchTerm) {
                  accounts = accounts.filter((a: any) =>
                    a.account_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                    a.account_code.toLowerCase().includes(searchTerm.toLowerCase())
                  );
                }

                const sectionClass = {
                  'Asset': 'bg-blue-50',
                  'Liability': 'bg-yellow-50',
                  'Equity': 'bg-green-50',
                  'Revenue': 'bg-purple-50',
                  'COGS': 'bg-gray-50',
                  'Expense': 'bg-red-50'
                }[sectionName] || 'bg-gray-50';

                return (
                  <React.Fragment key={sectionName}>
                    {/* SECTION HEADER – ALWAYS VISIBLE */}
                    <TableRow className={`${sectionClass} print:bg-gray-100`}>
                      <TableCell colSpan={4} className="font-bold py-3">
                        <div className="flex items-center justify-between">
                          <span>
                            {sectionName === 'COGS'
                              ? 'COST OF GOODS SOLD'
                              : sectionName.toUpperCase()}
                          </span>
                          <span className="text-sm font-normal">
                            {accounts.length} account{accounts.length !== 1 ? 's' : ''}
                            {searchTerm && ` (filtered)`}
                          </span>
                        </div>
                      </TableCell>
                    </TableRow>

                    {/* ACCOUNT ROWS */}
                    {accounts.length > 0 ? (
                      accounts.map((a: any) => (
                        <TableRow key={a.account_code} className="hover:bg-gray-50">
                          <TableCell className="font-mono text-sm">{a.account_code}</TableCell>
                          <TableCell>{a.account_name}</TableCell>
                          <TableCell className="text-right font-medium text-green-700">
                            {money(a.debit)}
                          </TableCell>
                          <TableCell className="text-right font-medium text-red-600">
                            {money(a.credit)}
                          </TableCell>
                        </TableRow>
                      ))
                    ) : (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center py-8 text-gray-400 italic">
                          {searchTerm
                            ? `No accounts matching "${searchTerm}" in this section`
                            : hideZero
                              ? 'All accounts in this section have zero balances'
                              : 'No accounts available for this period'}
                        </TableCell>
                      </TableRow>
                    )}
                  </React.Fragment>
                );
              })}
            </TableBody>

            <TableFooter>
              <TableRow className="bg-gray-900 text-white font-bold print:bg-black">
                <TableCell colSpan={2}>GRAND TOTAL</TableCell>
                <TableCell className="text-right text-green-300">{money(grand_totals.debit)}</TableCell>
                <TableCell className="text-right text-red-300">{money(grand_totals.credit)}</TableCell>
              </TableRow>
            </TableFooter>
          </Table>
        </div>
      </Card>

      {/* Print Instructions */}
      <div className="print:hidden text-sm text-gray-500 p-4 border rounded-lg bg-gray-50">
        <div className="flex items-center gap-2 mb-2">
          <Printer className="h-4 w-4" />
          <span className="font-medium">Printing Tips:</span>
        </div>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the "Print" button for a print-friendly version</li>
          <li>In print dialog, select "Save as PDF" to save as PDF</li>
          <li>For best results, choose landscape orientation</li>
          <li>Uncheck "headers and footers" in print settings for cleaner output</li>
        </ul>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .print-area, .print-area * {
            visibility: visible;
          }
          .print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}